### ISSUE TITLE
Example of using scss parser with gulp

### ISSUE THREAD

**Issue by asavin** [postcss/postcss-scss#10]
Would be great to see an example how postcss-scss could be used with gulp piping. [`gulp-postcss`](https://github.com/postcss/gulp-postcss) only provides an example of custom processor, but not a custom parser.

**Comment by ben-eb** [comment]
It's supported, but there's no documentation for it yet, see: https://github.com/postcss/gulp-postcss/issues/56

The gulp-postcss wrapper has the same API as a PostCSS instance would, so you can do something like this:

```js
var gulp = require('gulp');
var postcss = require('gulp-postcss');

gulp.task('default', function () {
  return gulp.src('in.css')
    .pipe(postcss([
      require('postcss-nested')
    ], {syntax: require('postcss-scss')})
    .pipe(gulp.dest('out'));
});
```

**Comment by asavin** [comment]
@ben-eb thanks, that worked!

**Comment by alexreg** [comment]
Still no documentation, all this time later, but thanks for creating and answering this issue at least!

**Comment by emmaYugen** [comment]
> It's supported, but there's no documentation for it yet, see: [postcss/gulp-postcss#56](https://github.com/postcss/gulp-postcss/issues/56)
> 
> The gulp-postcss wrapper passes through the same options object, so you can do something like this:
> 
> ```js
> var gulp = require('gulp');
> var postcss = require('gulp-postcss');
> 
> gulp.task('default', function () {
>   return gulp.src('in.css')
>     .pipe(postcss([
>       require('postcss-nested')
>     ], {syntax: require('postcss-scss')}))
>     .pipe(gulp.dest('out'));
> });
> ```

Hello. 
Thank you for the solution. 
I tried it and my error disappeared, but my scss is not compiled. 
In my dest folder, everything is sent in scss, folders and everything...

**Comment by ai** [comment]
PostCSS Sass does not complile Sass. You need to use Sass for that.
