### ISSUE TITLE
Parse Sass Module prefixes as part of value-word instead of value-word and value-operator

### ISSUE THREAD

**Issue by wegry** [postcss/postcss-scss#103]
https://sass-lang.com/documentation/at-rules/forward#adding-a-prefix is a relatively recent addition to Sass

```scss
@forward "src/list" as list-*;
```

I came across what looks like this parser parsing `list-` and `*` as separate nodes trying to patch up https://github.com/prettier/prettier/issues/7019.

**Comment by ai** [comment]
PostCSS should not parse content of at-rule.

Show what you get and what you want.

**Comment by wegry** [comment]
If it’s by design, that’s fine. We can work around it upstream.

Prettier (with my local modifications to support sass module syntax) is turning that `list-*` into `list- *` at the moment.

**Comment by ai** [comment]
Yeap, I am pretty sure that Prettier uses some another parser to parse at-rule params because PostCSS just returns a string for them
