### ISSUE TITLE
Types are missing from v2.1.0 published package

### ISSUE THREAD

**Issue by MaxMilton** [postcss/postcss-scss#106]
Thanks to #104 we now have TypeScript types included with the package which is fantastic, however, in the `2.1.0` release the `lib/scss-syntax.d.ts` file is missing.

Here are the files present in the release: <https://www.jsdelivr.com/package/npm/postcss-scss?path=lib>.

**Comment by ai** [comment]
Very strange. I will check it on next week.

Feel free to send PR if you will find a problem earlier.

**Comment by ai** [comment]
Fixed in 2.1.1 https://github.com/postcss/postcss-scss/commit/9080524784382fd73ec1ad8860a19755b56bda6c

**Comment by MaxMilton** [comment]
That was quick. Thank you! 🎉
