### ISSUE TITLE
Field not supported

### ISSUE THREAD

**Issue by cesarkohl** [postcss/postcss-scss#114]
Hey,

It seems my `postcss.config.js` file doesn't accept both fields `syntax` and `parser`.

**Warning: Your PostCSS configuration defines a field which is not supported (`syntax`). Please remove this configuration value.
Warning: Your PostCSS configuration defines a field which is not supported (`parser`). Please remove this configuration value.**

My package.json:
```
"postcss-flexbugs-fixes": "4.2.1",
"postcss-preset-env": "^6.7.0",
"postcss-scss": "^3.0.4",
"@fullhuman/postcss-purgecss": "^3.0.0"
```

How can I fix it?

**Comment by ai** [comment]
1. Show your `postcss.config.js`
2. What builder do you use? webpack/gulp/postcss-cli?

**Comment by Angelki** [comment]
I have the same issue, I use next@9.5.3 .

**Comment by ai** [comment]
@Angelki show your PostCSS config

**Comment by Angelki** [comment]
```js
module.exports = {
    syntax: 'postcss-scss',
    plugins: [
        'postcss-sassy-mixins',
        'postcss-import',
        'postcss-flexbugs-fixes',
        'postcss-advanced-variables',
        [
            'postcss-preset-env',
            {
                autoprefixer: {
                    flexbox: 'no-2009',
                },
                stage: 3,
                features: {
                    'custom-properties': false,
                    'nesting-rules': true,
                },
            },
        ],
        ['postcss-px2rem', { remUnit: 75 }],
    ],
};

```

**Comment by ai** [comment]
So you have the full stack trace?

I can't remember this error message. Maybe Next.js has own code to load the config.

**Comment by Angelki** [comment]
OK, I got it. The error is thrown by [this file](https://github.com/vercel/next.js/blob/8221c180a55828b39a7e1e01811365bfaaa0dd19/packages/next/build/webpack/config/blocks/css/plugins.ts#L127
) from next.js.  next.js does not support keys other than plugins.

**Comment by dzcpy** [comment]
Same issue, I was using `postcss-less`. I wonder where can I find the documentation for `postcss.config.js`? I googled a bit but can't find anything
