### ISSUE TITLE
Lists do not work

### ISSUE THREAD

**Issue by iniatse** [postcss/postcss-scss#117]
Scss code:

```
$colors: #4A75C6, #D9E2F3, #CF7262, #729328, #214079; // Royalblau;

svg.slider-arrow-svg {
	path {
		fill: nth($colors, 1);
	}
}
```

Current css ouput:

```
svg.slider-arrow-svg path {
		fill: nth(#4A75C6, #D9E2F3, #CF7262, #729328, #214079, 1);
	}
```

Expected css ouput:

```
svg.slider-arrow-svg path {
		fill: #4A75C6;
	}
```

Why does this not work as expected? Do I need a plugin or is this a too new feature of scss?

Thx

**Comment by ai** [comment]
`postcss-scss` do not compile SCSS. It just parse SCSS as a string `nth($colors, 1)`. `postcss-scss` was created for linters to lint SCSS sources with PostCSS tools.

In your case, PreCSS transforms variables. And PreCSS !== SCSS. It has a different syntax. And this is the right output for PreCSS.

Unfortunately, there is no way to compile SCSS to CSS via PostCSS.

**Comment by iniatse** [comment]
thank you
