### ISSUE TITLE
[QUESTION] Find declared variables only

### ISSUE THREAD

**Issue by danny007in** [postcss/postcss-scss#120]
- Is there any in-built function to find declared variables.
- It might be useful to this plugin https://github.com/XhmikosR/find-unused-sass-variables because it uses postcss-scss
- To avoid this https://github.com/XhmikosR/find-unused-sass-variables/blob/master/lib/parse-variable.js

**Comment by ai** [comment]
> Is there any in-built function to find declared variables.

```js
root.walkDecls(decl => {
  if (decl.prop.startsWith('$')) {
    console.log(decl.toString())
  }
})
```
