### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by semiromid** [postcss/postcss-scss#121]
Hello @ai 

Fatal error is not handled

As example

```
.y{

}


.q{


```

**Comment by ai** [comment]
> Fatal error is not handled

What is the current output and how do you want to handle it?

**Comment by semiromid** [comment]
@ai 

> how do you want to handle it

It would be ideal if it were possible to send error data to the function or `event.emit('postcss-error', error);`

As example:

```
  if(options.onError != undefined && typeof options.onError === 'function'){
      options.onError(error);
  }
```

> What is the current output

I am using grunt-postcss, and it does not yet have the ability to handle errors.

output - missing, because there was a fatal error

**Comment by ai** [comment]
You need to create an issue in `grunt-postcss`. Seems like `grunt-postcss` doesn't convert issue to Grunt event.
