### ISSUE TITLE
Invalid source start line and column values for nested declaration

### ISSUE THREAD

**Issue by niksy** [postcss/postcss-scss#129]
It seems like nested declaration source start line and column values are invalid, but source end values are OK. You can see the bug in [repl](https://replit.com/@niksy/postcss-scss-NestedDeclaration).

Input:

```scss
a {
  background: red {
    origin: padding-box;
  }
}
```

* Source start is `{ line: 6, column: 15 }`
* Source end is `{ line: 4, column: 3 }`

Source end should have lower line number than source start, right? If I’m looking at it correctly, correct value should be `{ line: 2, column: 3 }`.

I’ve created [PR](https://github.com/postcss/postcss-scss/pull/130) with possible fix.

**Comment by ai** [comment]
Thanks. The fix was released in 4.0.1.
