### ISSUE TITLE
ES2015 import needs * syntax

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-scss#13]
I installed this package via npm and tried to `import` it using ES2015 module syntax (compiled via babel).

However, because there is no `default` export, it seems, a straight `import` returns undefined:

```js
import scssSyntax from 'postcss-scss';
console.log(scssSyntax); // undefined
```

After looking at the source here, I was able to get an `import` to work using `*`:

```js
import * as scssSyntax from 'postcss-css';
console.log(scssSyntax);
/*
{ __esModule: true,
  parse: [Function: scssParse],
  stringify: [Function: scssStringify] }
*/
```

Sorry again for the confusion with the unintentional commit.

**Comment by ben-eb** [comment]
@ai Could we do something like this?

```js
import stringify from './scss-stringify';
import parse     from './scss-parse';

let syntax = {parse, stringify};
export default syntax;
```

Leaving the destructuring to the consumer of the module?

**Comment by ai** [comment]
Done 49e5e45

**Comment by ai** [comment]
@davidtheclark thanks for finding this bug.

Released in 0.1.3.

**Comment by davidtheclark** [comment]
Cool thanks!

**Comment by ben-eb** [comment]
:+1:
