### ISSUE TITLE
Fails to require("postcss-scss") module `v4.x`

### ISSUE THREAD

**Issue by phoenisx** [postcss/postcss-scss#136]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/11786283/153771377-08c586b4-a128-4192-b00b-d8225accde8f.png">

Till `v3.x`, `require("postcss-scss")` works fine, but is failing for any `4.x` version.

Also, if you see [Bundle Details](https://bundlephobia.com/package/postcss-scss@4.0.3), the size of the package has dropped significantly, not sure if this was intended, but maybe some package is missing from the bundle.

Anyways, I can take a look next weekend.

**Comment by ai** [comment]
Can you show the full error stack trace?

**Comment by phoenisx** [comment]
Apologies! I should've attached it before.

```sh
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (node_modules/postcss-scss/lib/nested-declaration.js:3:33)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by ai** [comment]
Can you show what version of `postcss` do you have in your `package.json`?

**Comment by phoenisx** [comment]
@ai 
I do not have a direct dependency on `postcss` in the project; instead, it's transitive.
Since I am building an [extension](https://github.com/willofindie/vscode-cssvar/) that uses `postcss` but doesn't include any `plugin` / `syntax` modules, it's left for the user to install if they need extra features, to keep the extension size small.

Even with transitive dependency,`require(postcss-less@6)` works, but `require(postcss-scss@4)` fails.
Once I installed `postcss@8.4.6` as a direct dependency, `postcss-scss` require started working.

_**Is there a way to pass `postcss` module as a param to these `plugin` / `syntax` modules?? Or can we add a check instead of failing to require the module**_

**Comment by ai** [comment]
Seems like this error are going from the fact that you are using `postcss` 7, but `postcss-scss` requires `postcss` 8.

You need to add `postcss` 8 to `peerDependencies` of your tool and install `postcss` 8 to `devDependencies`.

> Or can we add a check instead of failing to require the module

You can get current PostCSS version by calling `postcss().version`
