### ISSUE TITLE
Twice "grid-gap" in output css file

### ISSUE THREAD

**Issue by chshchnkv** [postcss/postcss-scss#139]
I have a "gap" property in class:

```
.example {
  display: flex;
  gap: 10px;
}
```

In the output css-file it will be:

```
.example {
  display: flex;
  grid-gap: 10px;
  grid-gap: 10px;
  gap: 10px;
}
```

This isn't urgent but FYI.

**Comment by ai** [comment]
Show you PostCSS config?

What tool do you use to compile CSS?

**Comment by ai** [comment]
Strange. Seems like somebody run Autoprefixer twice or apply some other tool to CSS after `postcss-preset-env`.

Sorry, this repo is for PostCSS core and this is an environment and configuration problem, rather than an issue in the core. It is better to ask Rollup community.
