### ISSUE TITLE
Q: Support indented syntax?

### ISSUE THREAD

**Issue by hinell** [postcss/postcss-scss#14]
I mean the syntax without curl-like braces as described here
http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html

```sass
#main
  color: blue
  font-size: 0.3em

  a
    font:
      weight: bold
      family: serif
    &:hover
      background-color: #eee
```

**Comment by ben-eb** [comment]
Shouldn't be this module's responsibility; someone should create `postcss-sass` to handle this.

**Comment by ai** [comment]
Nope. This SCSS (syntax with brackets) parser, not Sass parser.
