### ISSUE TITLE
[Question] Can we add `lib/scss-parser.js` in package.json `exports` list

### ISSUE THREAD

**Issue by phoenisx** [postcss/postcss-scss#140]
It's effortless to extend `postcss` and any of its internal modules. `lib/parser.js` (from `postcss`) module is also exported in `package.json`, which makes it easy to extend `postcss` parser in any project.
**_Is it okay if we can do the same for this package as well?_**

I am asking this because there might be use cases where a developer just wants to extract the SCSS parser from this library and extend it, for e.g. extend it with `safe-parser`.

**Comment by ai** [comment]
Sure, why not. Send PR.
