### ISSUE TITLE
Syntax error not recognized

### ISSUE THREAD

**Issue by zaalbarxx** [postcss/postcss-scss#148]
Hi!
Based on discussion here [https://github.com/stylelint/stylelint/issues/7173](url) it was pointed out that I should create an issue regarding the "silent" parsing error here. Basically when passing SCSS like that 
```
<style lang="scss" scoped>
@use "sass:map": // colon instead of semicolon

.test {
    margin-top: $spacers, 3); //missing (
}
</style> 
```
the plugin seem to parse this code without error even though there are indeed some syntax errors here. Is it a normal behavior and should remain unfixed or maybe it should have been patched ? My idea behind all of this is that I should be able to lint the CSS just like I would lint the JS. ESLint will always return parsing error if it finds something wrong with the syntax of code. I'd expect same from the Stylelint.

**Comment by ai** [comment]
Both PostCSS and PostCSS SCSS parses it because it is pass CSS syntax. You need to validate at-rules to find that `@use` can't have this syntax inside

**Comment by ai** [comment]
PostCSS is not a validator, you need to do it in some plugin
