### ISSUE TITLE
Question: Will this parse nested scss? 

### ISSUE THREAD

**Issue by smustgrave** [postcss/postcss-scss#149]
May be dumb but looking to see if I want to convert to postcss and the library we have ot use, uswds, is sass

**Comment by ai** [comment]
Yes, it will parse nested SCSS:

```scss
a {
  b {
  }
}
```

But, it will not convert it to CSS. It will just parse it as is. You need some plugin to change the source.

We don’t have plugins to convert any SCSS to CSS (it is better to use `scss` CLI).

But you can write your own plugin to cover some limited cases which you have in your project (and avoid covering all cases which is really hard).
