### ISSUE TITLE
How to understand if a comment was converted?

### ISSUE THREAD

**Issue by borodean** [postcss/postcss-scss#15]
To fix https://github.com/stylelint/stylelint/issues/519 it is needed to distinguish which comments are block, and which were line ones. The later ones should then be skipped by the rule check.

I've tried to find a way to distinguish what were the original comments inside plugin's code, but the best option I came up with was looking at `source.input.css`, splitting it into lines, then picking the provided line and column, then checking if its `//` or `/*`.

Could you please help me to find out if there is a better way? Maybe PostCSS or postcss-scss could be improved to support that? I'm eager to help.

**Comment by ben-eb** [comment]
Use `node.raws.inline`.

https://github.com/postcss/postcss-scss/blob/c32cc4c453228eae2f7f6ae3320cfa1d7d09b6e7/lib/scss-parser.es6#L16

**Comment by borodean** [comment]
@ben-eb fantastic, thanks.
