### ISSUE TITLE
Can not parse Interpolation

### ISSUE THREAD

**Issue by energy718** [postcss/postcss-scss#152]
https://stackblitz.com/edit/vitejs-vite-aqxsuv?file=src%2Fstyles.mscss

Hi I wrote a vite plugin to parse custom file to css, I found `Interpolation` can not be parsed correctly by parser 
![image](https://github.com/user-attachments/assets/fdd885b8-2300-4531-8e3e-696264e32cfa)

**Comment by ai** [comment]
Can you show the bug in isolated environment where you have only postcss-scss (for instance, by using JS API and showing input and real/expected output)?

In your example you show compiled CSS (nested blocks are unwrapped, variables are replaced), but this parser doesn't do compilation. So it could be a compiler issue.

**Comment by energy718** [comment]
Well, I see. I will use sass compiler to compile these code. Thx~
