### ISSUE TITLE
Is there any plan to support operators?

### ISSUE THREAD

**Issue by anker-leon** [postcss/postcss-scss#17]
Hello, 
scss:
```
padding: 12px * 2;
```

http://sass-lang.com/guide#topic-8

**Comment by ben-eb** [comment]
Use https://github.com/TrySound/postcss-value-parser for this. :smile:

**Comment by TrySound** [comment]
@anker-leon It's just a parser, not processor

**Comment by anker-leon** [comment]
OK, thanks to both of you.
