### ISSUE TITLE
@content support.

### ISSUE THREAD

**Issue by sccorby** [postcss/postcss-scss#22]
First of all, this is a an awesome postcss plugin that has helped my workflow tremendously. 

The issue is when using scss mixins that contain th @content at rule, postcss fails. This is likely because it appears to be a property without a value.

**Comment by TrySound** [comment]
@sccorby postcss-scss is not plugin, it's parser/stringifier. And any at-rules are parsed fine. Show your error log.

**Comment by ai** [comment]
@sccorby please show your SCSS inpput.

**Comment by sccorby** [comment]
@TrySound Yes I am aware that postcss-scss is not a plugin that manipulates or compiles scss. But it is technically a plugin for postcss that extend's postcss's ability to parse css to included scss syntax. We are using postcss-scss to parse our scss before it has been compiled, so we can do thinks like autoprefix properties directly to the scss, instead of to the final compiled css. 

@ai The scss input is simple, it contains only the following:

`@mixin video-controls($name) {
    .video-js .vjs-#{$name} {
        @content;
    }
}`

Post-css fails to parse the above code, while the below code does not throw an error:

`@mixin video-controls($name) {
    .video-js .vjs-#{$name} {
        //@content;
    }
}`

Error stacktrace is below:

`TypeError: Cannot read property 'replace' of undefined
    at /Users/scorby/Desktop/specless-cascade-app/build/utils/processCss.parseContexts.js:117
    at /Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:73
    at Rule.each (/Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:60)
    at Rule.walk (/Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:72)
    at /Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:76
    at AtRule.each (/Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:60)
    at AtRule.walk (/Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:72)
    at /Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:76
    at Root.each (/Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:60)
    at Root.walk (/Users/scorby/Desktop/specless-cascade-app/build/node_modules/postcss/lib/container.js:72)`

**Comment by sccorby** [comment]
I have located the issue in our own code.Postcss-scss parses the scss correctly, we just anticipated all at-rules to have a defined value for everything for everything between the at-rule itself, and the `;` or `{`.

False alarm!
