### ISSUE TITLE
Colon in comment - error "Missed semicolon"

### ISSUE THREAD

**Issue by Igloczek** [postcss/postcss-scss#28]
Part of `_variables.scss` file:
```scss
// Media query
// ---------------------------------------------
// two variable used inside magento 2 to set media query 2 features:
// 1 - "common" options, different in emails and style_l
// 2 - "target" all, desktop or mobile devices
$media-common: true; // Sets whether to output common styles (true|false)
$media-target: 'all'; // Sets target device for styles output (all|desktop|mobile)
```
Error:
```
[current_path]/_variables.scss:12:40: Missed semicolon
// 1 - "common" options, different in emails and style_l
// 2 - "target" all, desktop or mobile devices
                                       ^
$media-common: true; // Sets whether to output common styles (true|false)
```

If I remove `:` after `features` everything works fine, but if I put them somewhere else, also breaks and it points same, completly not revelant, place in code.... #weird

**Comment by ai** [comment]
Wierd. But I will have time to look on it only in weekend. Is it OK?

**Comment by Igloczek** [comment]
I try to use this syntax parser to lint scss files, but got errors almost on every line... (mostly line comments `//` and variables) So unfortunately, I have to switch to standalone sass-lint, but definitely looking forward to back to stylelint scss files linting.

If you want more feedback or source files, feel free to ask.

**Comment by ai** [comment]
Strange. I test with source and `postcss-scss` parsed it without any problems. Could you show full stacktrace? Maybe you forget to change a parser?

**Comment by Igloczek** [comment]
I'll try to create demo, to reproduce this problems.

**Comment by Igloczek** [comment]
That's was my fault, I fucked up some part of config...

**Comment by ai** [comment]
Maybe it is a Stylelint issue? @davidtheclark why Stylelint allows to process `*.scss` files with CSS syntax. Does Stylelint change parser automatically by file ext?
