### ISSUE TITLE
Not parsing '!default'

### ISSUE THREAD

**Issue by antoniocanas** [postcss/postcss-scss#29]
Using UIKit I noticed this:
```
.uk-margin-small-bottom {
    margin-bottom: 5px !default !important;
}
```
It's not removing '!default' from variables, so final CSS won't work

**Comment by ben-eb** [comment]
> **This module does not compile SCSS.** It simply parses mixins as custom at-rules & variables as properties, so that PostCSS plugins can then transform SCSS source code alongside CSS.

Use Sass for compilation, not this module.

**Comment by ai** [comment]
Yeap, sorry, but this feature can be done only by PR :).

`!default` is not part of standard CSS, so most of PostCSS plugins will not care about it.

Why you need to parse it separately for PostCSS plugins?
