### ISSUE TITLE
Problem with compiling custom html elements styling

### ISSUE THREAD

**Issue by TomaszScisloGS** [postcss/postcss-scss#35]
Hi!

I use postcss-loader with postcss-scss in webpack and sometimes file which contains styling for custom HTML element

<m-element><my-element>

my-element{
/* some styles*/
}

Is not compiled at all and sometimes it's compiled without issues. Is this type of styling supported or not?

Thanks!

**Comment by ai** [comment]
Please show output or error message.

**Comment by TomaszScisloGS** [comment]
Well there is none error message. Simply sometimes code form this file is not taken into account. Are custom HTML elements supported in postcss-sccs>

**Comment by ai** [comment]
Show some input and output examples

**Comment by TomaszScisloGS** [comment]
This is the input

gs-query-auto-complete {
  display: table
}

It's not in the output

**Comment by TomaszScisloGS** [comment]
Moreover such a scss also results in this problem and it's not compiled correctly

[class^="admin"] {

}

**Comment by ai** [comment]
I tested your CSS and everything fine.

Here is test JS:

```js
var syntax = require('./');

var css = 'gs-query-auto-complete {\n' +
'display: table\n' +
'}\n' +
'\n' +
'[class^="admin"] { }';

console.log(syntax.parse(css).toString());
```

And it’s output:

```css
gs-query-auto-complete {
display: table
}

[class^="admin"] { }
```

**Comment by ai** [comment]
Maybe some PostCSS plugin removed these rules? Or some other tools?
