### ISSUE TITLE
Does this plugin expose any metadata about imports?

### ISSUE THREAD

**Issue by apexskier** [postcss/postcss-scss#37]
I'm working on a postcss plugin and want to inspect postcss nodes for their original scss file. For example: I have a comment node and I want to act on it if the original scss file it was in was in a certain directory.

Does this plugin expose any information like this or add any context to a postcss result?

**Comment by ai** [comment]
This parser stores origin node’s file in `Node#source` (same as default parser)

**Comment by apexskier** [comment]
Thanks. My problem's actually related to something else, but that helps me a lot.
