### ISSUE TITLE
Does the plugin work with Webpack?

### ISSUE THREAD

**Issue by Janekk** [postcss/postcss-scss#43]
Tried to set it up with:

```
postcss: [(...), require('postcss-scss')(), (...)]
```

(like with other postcss plugins, e.g. `require('postcss-import')()`) but got: 

```
Module build failed: TypeError: require(...) is not a function
```

**Comment by ai** [comment]
`postcss: []` sets plugins, not a parser. To change a parser you need to use `?parser` parameter like `style!css!postcss?parser=postcss-scss`
