### ISSUE TITLE
scss function parsing error

### ISSUE THREAD

**Issue by Tux1** [postcss/postcss-scss#44]
Hi,
What is the best way to handle scss functions ?
Because I import a theme written in scss and it contains scss functions that postcss doesn't handle properly. 
How can I deal with that without rewriting the theme myself ?

Thanks

**Comment by ai** [comment]
Could you show input SCSS and error with stacktrace?

**Comment by Tux1** [comment]
Apologies, I set scss as syntax not as parser. it works now.

**Comment by Tux1** [comment]
Actually, even before it crashes : 

> ERROR in ./~/css-loader?{"sourceMap":false,"modules":true,"localIdentName":"[hash:base64:4]","minimize":true}!./~/postcss-loader!./components/WidgetPane/styles.scss
> Module build failed: Missed semicolon (2:0)
> 
>   1 | @import "scss/mgb.scss";
> > 2 | // TODO: Replace hex by variable
>   3 | $border-color: #e6e6e6;
>   4 | 
>   5 | .widget-pane {
> 
>  @ ./components/WidgetPane/styles.scss 4:14-222

my config:
```
var syntax = require('postcss-scss');
postcss() {
return {
  plugins: [
    require('autoprefixer')(),
  ],
  syntax,
};
```

and the file :
```
@import "scss/mgb.scss";
// TODO: Replace hex by variable
$border-color: #E6E6E6;

.widget-pane {
  font-weight: 400;
  line-height: 1;
}
```

Btwm `scss` is an webpack alias

Many thanks!

**Comment by ai** [comment]
Seems like you didn‘t change the parser. This error could throw only from default CSS parser. Your need to install `postcss-scss` and explicit change the parser by `postcss-loader?parser=postcss-scss`.

Very strange that `postcss-loader` did warn you about wrong parser. Maybe you use old PostCSS?

**Comment by Tux1** [comment]
I use `postcss` 5.1.1, I think it is the latest. (all my packages are updated)
Maybe it comes from the loader ? 
   ```
   {
        test: /\.scss$/,
        loaders: [
          'style-loader',
          `css-loader?${JSON.stringify({
            sourceMap: isDebug,
            modules: true,
            localIdentName: isDebug ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]',
            minimize: !isDebug,
          })}`,
          'postcss-loader?parser=postcss-scss',
        ],
      },
```

**Comment by ai** [comment]
It is not the latest. Latest is 5.2

**Comment by ai** [comment]
Hi, where do you have sass-loader to compile SCSS to CSS?

**Comment by Tux1** [comment]
This version is not available on npm

**Comment by Tux1** [comment]
I don't have sass-loader

**Comment by ai** [comment]
Em. So why you use SCSS if you don't have Sass Loader?

**Comment by ai** [comment]
This error happens because you send SCSS sources to css-loader, but it supports only CSS.

**Comment by Tux1** [comment]
So what is the purpose of this plugin ?

**Comment by ai** [comment]
This loader runs PostCSS. PostCSS doesn't support Sass. You could add scss-loader for Sass sources.

**Comment by Tux1** [comment]
So what is the purpose of `postcss-scss` if it is not to run Sass sources ?

**Comment by ai** [comment]
Just use scss-loader, then postcss-loader, then css-loader and in the final style-loader.

Unfortunately, webpack is not friendly in config 😞.

**Comment by ai** [comment]
Please, read README more careful. This parser parse SCSS sources as is. But it doesn't compile it to CSS. You will have SCSS again after PostCSS.
