### ISSUE TITLE
Mixin variable interpolation generating bugs after nested properties support

### ISSUE THREAD

**Issue by DanielaValero** [postcss/postcss-scss#45]
Hello,

After the version 0.2.0, when the nested props have been added, interpolating variables in mixins is not working as before. 

```
1 @mixin name($var) {
2  &:#{$var} {}
3 }
```

I am using this plugin together with stylelint to lint my styles, the line 2 in the snippet before, creates a false negative with stylelint. Initially I thought it was related to stylelint and raised a bug in there, afterwards, after tracking this down a bit more, realized that it is related to the new feature of nested properties.

I could not understand deeply how the new nested props works, however I tend to think that this syntax is not yet added?

I wish I could be more specific with my report, but I am willing to help with questions if required.

https://github.com/stylelint/stylelint/issues/1936

**Comment by ai** [comment]
Done 1f4e98c

**Comment by ai** [comment]
Fix release in 0.3.1. Thanks for report :)
