### ISSUE TITLE
Error: Unknown word when using sass's `map-get`

### ISSUE THREAD

**Issue by tiemevanveen** [postcss/postcss-scss#46]
I'm getting this error then using `map-get`.

```diff
ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/table.scss
Module build failed: Unknown word (15:12)

  13 |
  14 | @mixin mediaquery($name) {
> 15 |   @media #{map-get($breakpoints, $name)} {
     |            ^
  16 |     @content;
  17 |   }
```

I've tried using the loader like this `'postcss-loader?parser=postcss-scss',` but without success:

```diff
ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./~/postcss-loader?parser=postcss-scss!./src/utils.scss
Module build failed: CssSyntaxError: /Users/Tieme/Projects/Repos/react-css-modules-examples/utils.scss:15:4: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
    at Input.error (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/postcss/lib/input.js:111:22)
    at Parser.unknownWord (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/postcss/lib/parser.js:457:26)
    at Parser.other (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/postcss/lib/parser.js:174:14)
    at Parser.loop (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/postcss/lib/parser.js:81:26)
    at parse (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/postcss/lib/parse.js:26:16)
    at new LazyResult (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/postcss/lib/processor.js:117:12)
    at processCss (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/css-loader/lib/processCss.js:188:11)
    at Object.module.exports (/Users/Tieme/Projects/Repos/react-css-modules-examples/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./~/postcss-loader?parser=postcss-scss!./src/table.scss 3:10-217
``` 

Example repo: https://github.com/tiemevanveen/react-css-modules-examples/tree/scss-postcss

**Comment by ai** [comment]
I try to look today or tomorrow.

Feel free to ping me in Monday if I will not write you.

**Comment by tiemevanveen** [comment]
Cool. I'll provide you with an example.

**Comment by tiemevanveen** [comment]
Just for my understanding. With these loaders:

	loaders: [
	    'style',
	    'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
	    'postcss',
	    'sass'
	]

This should happen right:

1. Sass loader parses sass
1. Sass loader outputs css
1. PostCss loader's input is only valid css
1. PostCss uses plugins, transforms css

So I would never need the postcss-scss plugin at all right?

But If I don't use it, PostCSS still fails and recommends to use it. Does that make sense? I've got the feeling I'm missing something here. Could the used react-css-modules / css-modules have something to do with the problem?

**Comment by ai** [comment]
Don't worry, I know a error issue 😊. I am not home, but I think I will just tokenizer.

**Comment by tiemevanveen** [comment]
Same for `inspect` btw. See http://sass-lang.com/documentation/Sass/Script/Functions.html#inspect-instance_method

For example:

```
$breakpoints: (
  'mobile'           : ( max-width:   413px ),
  'phablet'          : ( max-width:   767px ),
  'tablet-portrait'  : ( max-width:  1023px ),
  'tablet-landscape' : ( max-width:  1279px ),
);

@mixin mediaquery($name) {
  // If the key exists in the map
  @if map-has-key($breakpoints, $name) {
    // Prints a media query based on the value
    @media #{inspect(map-get($breakpoints, $name))} {
      @content;
    }
  }

  @else {
    @warn "No value for `#{$name}` could be retrieved from `#{$breakpoints}`"
  }
}
```

**Comment by ai** [comment]
I tested your example with latest `postcss-scss` and it compiles it without any syntax error.

Do you use latest `postcss-scss`?

**Comment by tiemevanveen** [comment]
Yeah, just did a fresh install from npm. But using webpack v1.. would that matter?

**Comment by ai** [comment]
webpack is not relevant.

Maybe you could create test project to reproduce issue?

**Comment by tiemevanveen** [comment]
Yeah. I'll re check my example.

But just for my info. Is it correct that I would need postcss-scss in this case? And if so, why is that? The sass loader should handle all these things just fine right?

**Comment by ai** [comment]
Yeap, source example looks correct for Sass syntax (but I am not big Sass user 😉)

**Comment by tiemevanveen** [comment]
> Yeap, source example looks correct for Sass syntax (but I am not big Sass user 😉)

Yeah the sass is valid (and worked fine before), but I mean, Why would I need ` postcss-scss` in the first place. By the time the source is loaded by postcss it should contain no sass any more but plain old css right? 
 
Just tested it again, here's the full log: https://gist.github.com/tiemevanveen/1f2182c11c9922faad76fb41ce7414ef 

And if you run this, all is fine right? 

```
$ git clone -b scss-postcss --single-branch git@github.com:tiemevanveen/react-css-modules-examples.git test
... 
$ cd test
$ npm i
... 
$ git log -2 --decorate
... 
$ npm start

ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/utils.scss
Module build failed: Unknown word (15:14)

  13 |
  14 | @mixin mediaquery($name) {
> 15 |     @media #{map-get($breakpoints, $name)} {
     |              ^
  16 |         @content;
  17 |     }
```

**Comment by ai** [comment]
Yeap, most of Sass users doesn’t need a `postcss-scss` at all (because Sass compiles SCSS to CSS and PostCSS works with CSS).

You need `postcss-scss` mostly for 2 cases:

1. Check SCSS sources by Stylelint.
2. Sort properties in SCSS sources by postcss-sorting.

**Comment by ai** [comment]
Seems like you just have webpack configuration issue and send SCSS to PostCSS before Sass.

**Comment by tiemevanveen** [comment]
The problem seems to be the combination of CSS Modules + SASS + PostCSS. I've created another (smaller) example and will try to find out the problem https://github.com/tiemevanveen/sass-css-components-fail-example. Thanks for your time :)

**Comment by ai** [comment]
Sorry, I am not a webpack user :(. Maybe you should ask in webpack stack.

This error is not relevant to PostCSS. It happens only because webpack send Sass sources to PostCSS instead of CSS.

**Comment by tiemevanveen** [comment]
No problem. Yeah indeed.. Thanks.

**Comment by tiemevanveen** [comment]
> Seems like you just have webpack configuration issue and send SCSS to PostCSS before Sass.

Got it. `importLoaders` should have been equal to the number of loaders. So `sass` + `postcss` = `2`.. 

This worked:


      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style-loader', [
          'css?modules&importLoaders=2&localIdentName=[path]_[name]_[local]',
          'postcss-loader',
          'sass'
        ])
      },

**Comment by lenouber** [comment]
I would like to create a custom theme for my new project.

1) I create a new file called custom-theme.scss in which I just write 
@import "~@angular/material/_theming.scss";
I can't use @import '~@angular/material/theming'; because this file doesn't exist ("@angular/cli": "1.6.7")

2)  I add a new entry in .angular-cli.json
 "styles": [
        "styles.css",
        "custom-theme.scss"
   ],
3) I add a line to my empty file styles.css :
@import "./custom-theme.scss";

**Comment by ai** [comment]
@lenouber can you open a new issue with input SCSS?
