### ISSUE TITLE
how do you use this with webpack

### ISSUE THREAD

**Issue by craigcosmo** [postcss/postcss-scss#49]
I tried this, it's not working

this is my webpack config

```js
import precss from 'precss'
import scss from 'postcss-scss'

export default {
	module: {
		loaders: {
			test: /\.pcss$/,
			loader: ExtractTextPlugin.extract('style-loader!css-loader?sourceMap!resolve-url-loader!postcss-loader?sourceMap')
		},
	},
	postcss: function () {
		return [precss,scss]
	},
	
}
```

the error produces 

```
ERROR in ./~/css-loader?sourceMap!./~/resolve-url-loader!./~/postcss-loader?sourceMap!./app/component/header/header.pcss
    Module build failed: Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/Users/craigcosmo/Dropbox/Code/thatilike front/node_modules/postcss/lib/processor.es6:108:23)
```

**Comment by ai** [comment]
1. webpack doesn’t support `postcss` key. You should use `postcss.config.js` config https://github.com/postcss/postcss-loader#usage
2. `postcss-scss` is not a plugin. You should pass it by `postcss-loader?parser=scss`

**Comment by ai** [comment]
I made better error message for cases like your https://github.com/postcss/postcss/commit/da790db2438726e9c341233928adfa4c708ef6c4

**Comment by ai** [comment]
Better error message was released in PostCSS 5.2.7.

**Comment by EliRobinson** [comment]
Just for clarity, as there isn't any true documentation on the "correct syntax" out there.

The correct parser is:
postcss?parser=postcss-scss

Not to be confused with @ai's above comment regarding parser=scss.

**Comment by blachawk** [comment]
@EliRobinson I apologize for the stupid question, but when you say:

> postcss?parser=postcss-scss

..where do we put that line of code in our webpack.config.js file?

My current setup looks like this...

```
 {
            loader: 'postcss-loader',
            options: {
              parser:'sugarss',
            }
          },
```

**Comment by EliRobinson** [comment]
> @EliRobinson I apologize for the stupid question, but when you say:
> 
> > postcss?parser=postcss-scss
> 
> ..where do we put that line of code in our webpack.config.js file?
> 
> My current setup looks like this...
> 
> ```
>  {
>     loader: 'postcss-loader',
>       options: {
>         parser:'sugarss',
>        }
>   },
> ```

Not sure if the syntax is still relevant in the latest webpack, but it'd look like this probably.

```
rules: [
  {
    test: /\.css$/,
    use: [
      // sass-loader
      { loader: 'postcss?parser=postcss-scss' }
    ]
  }
]
```

 Otherwise, using the parser attribute might make more sense.
```
rules: [
  {
    test: /\.css$/,
    use: [
      // sass-loader
      { loader: 'postcss',
        parser: {
          postcss-scss: true,
        },
      },
    ],
  },
],
```
