### ISSUE TITLE
can this comment the whole class?

### ISSUE THREAD

**Issue by craigcosmo** [postcss/postcss-scss#50]
I don't know how to install this, but I have a quesiton

can I comment like this?

```css
//.home{
//   color:red
//}
```

**Comment by ai** [comment]
Yes

**Comment by craigcosmo** [comment]
Ok it doesn't to work like that.

My webpack config

```js
loader: 'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]___[hash:base64:5]'
```

my postcss config

```js
module.exports = {
	plugins: {
		'postcss-import': {},
		'postcss-cssnext': {
			browsers: ['last 2 versions', '> 5%'],
		},
	},
}
```

my style.css
```css
.home {
	// a {
	// 	margin-right: 20px;
	// }
	// .lego{
	// 	font-size: 10px;
	// }
}
```

error message

<img width="560" alt="screen shot 2017-01-01 at 1 02 14 am" src="https://cloud.githubusercontent.com/assets/538657/21578735/410593d2-cfbe-11e6-866b-ae800b077860.png">

**Comment by ai** [comment]
Could you try `&parser=postcss-scss`.

I think we have a UX issue in `postcss-loader` that it doesn’t throw a error on wrong parser.

**Comment by craigcosmo** [comment]
thanks finally I got it to work.

```js
{ loader: 'postcss-loader?sourceMap&parser=postcss-scss'},
```

**Comment by ai** [comment]
Strange. I tested unknown `parser` in `postcss-loader` and it failed with reasonable error description.
