### ISSUE TITLE
Unknown word error

### ISSUE THREAD

**Issue by timgrafton** [postcss/postcss-scss#53]
I'm having this error. I believe its something to do with this parser. Any help would be great, thanks. :)

![image](https://cloud.githubusercontent.com/assets/5726488/22928281/85605dd4-f2ad-11e6-8547-cdc9c3fce084.png)

**Comment by ai** [comment]
Please give a full stacktrace and input CSS file.

**Comment by timgrafton** [comment]
[error.zip](https://github.com/postcss/postcss-scss/files/774402/error.zip)

**Comment by ai** [comment]
I need `./~/bootstrap-sass/assets/stylesheets/_bootstrap-custom.scss` content. Post it on gist please, zip is not popular way in open source.

**Comment by timgrafton** [comment]
https://gist.github.com/timgrafton/e496551d2e756cd2380f7f22fa5917b2

**Comment by ai** [comment]
I tested this file and everything works well. Try to make some very small project to reproduce issue.
