### ISSUE TITLE
How to use bootstrap-sass mixins and variables?

### ISSUE THREAD

**Issue by saeidalidadi** [postcss/postcss-scss#54]
I need to import my `css (.scss)` files into `.js` (component architecture) and the base framework that I am using is `bootstrap-sass`.
Now I have these problem:

1. `bootstrap-sass` variables and mixins are not available inside my `.scss` files for every individual component.
2. I need to have `scope` for `.scss` files inside component.(css module)
3. I use webpack for bundling.

So the question is how can I import and transform my `css` files without losing `bootstrap-sass` variables and mixing also using the variables in their own scope ?

This is my `webpack.config.js` for bundling style files:
 
```javascript
module: {
      rules: [
        {
          test: /\.scss$/,
          use: [
            {
              loader: 'style-loader' // creates style nodes from JS strings
            }, {
              loader: 'css-loader' // translates CSS into CommonJS
            }, {
              loader: 'sass-loader' // compiles Sass to CSS
            }
          ]
        }
```

**Comment by ai** [comment]
I am not sure what exactly you want to do with SCSS variables and mixins. But it is the best way to convert SCSS to CSS-in-JS (*without* compiling SCSS to CSS)

```
{
  loader: 'postcss-loader',
  options: {
    parser: require('postcss-scss'),
    stringifier: require('postcss-js')
  }
}
```
