### ISSUE TITLE
Disable conversion of inline scss to css comments?

### ISSUE THREAD

**Issue by benebun** [postcss/postcss-scss#55]
Is there a way to disable the conversion of inline scss comments to css comments? I'm not sure what the rationale is to have it by default, I guess I'm missing something obvious.

We are using postcss-scss to be able to use autoprefixer on scss and output scss (not css). The compilation to css then happens serverside on a simple stack (which we would like to keep simple).

postcss-scss however converts scss comments `//` to css comments `/* */` and sassdoc comments `///` to `/*/ … */`. We would like to avoid this because that makes our serverside compilation more tricky (e.g. can't remove Sass comments anymore because they are not CSS comments).

Maybe I'm missing a better way…

Thanks!

**Comment by ai** [comment]
Sure. Just replace `parser: require('postcss-scss')` to `syntax: require('postcss-scss')`.

**Comment by benebun** [comment]
Wow, that was quick. Thanks! :)

**Comment by solid-pixel** [comment]
@ai @benebun sorry about the dumb question but how would I apply this solution to the atom-autoprefixer?

**Comment by ai** [comment]
@solid-pixel sorry, don’t use atom-autoprefixer and don’t know
