### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by svipben** [postcss/postcss-scss#57]
Hello,

Everything is explained here: https://github.com/shinnn/vscode-stylelint/issues/65#issuecomment-292880983

**Comment by ai** [comment]
@svipben I need input SCSS file and stacktrace

**Comment by svipben** [comment]
@ai the problem was with `.css` file if you mean that. Somehow I don't know how it's related with plugin for vs code which is `stylelint`, but I get this problem, opened an issue and repo owner said you need to open it here, because it isn't my problem. :smile: But if you need more info I can provide.

**Comment by ai** [comment]
I need file content and full stack trace.

**Comment by svipben** [comment]
Error happens if I write `:`, doesn't matter where you write `:` symbol, but if you write it, you will get this error:

`
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 TypeError: Cannot read property '0' of undefined     at Parser.decl (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:203:25)     at Parser.other (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:170:18)     at Parser.loop (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:81:26)     at parse (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parse.js:26:16)     at new LazyResult (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/lazy-result.js:70:24)     at Processor.process (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/processor.js:117:12)     at getCode.then.e (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/stylelint/lib/getPostcssResult.js:83:29)
`

File content:
`
:global(.test) {
  color: red;
}
`

Used tools: stylelint and stylelint plugin for VS Code and also VS Code.

Maintainer of stylelint plugin said this:

> In this case, stylelint.lint() must be rejected with CssSyntaxError rather than TypeError. Open a new issue on https://github.com/postcss/postcss-scss instead.

Here is the plugin: https://github.com/shinnn/vscode-stylelint
Here is the opened issue with maintainer @shinnn explaining: https://github.com/shinnn/vscode-stylelint/issues/65#issuecomment-292880983

I hope this is what you want.

**Comment by ai** [comment]
@shinnn why you send him in SCSS parser? Stacktrace shows that this error came from regular parser, but maybe I don't know something.

@svipben can you open JS code of PostCSS from stacktrace and put `console.log` to check what is origin CSS input to PostCSS. This input should be parsed without problem. So I think input is different.

**Comment by shinnn** [comment]
> why you send him in SCSS parser? Stacktrace shows that this error came from regular parser

@ai Yeah, I just tested again and confirmed it's not a SCSS-specific issue.

> This input should be parsed without problem. So I think input is different.

@svipben's explanation is really confusing so I created the smallest possible example here:

```js
'use strict';
const postcss = require('postcss');
console.log(postcss().process(':').error)
```

↓

```
TypeError: Cannot read property '0' of undefined
    at Parser.decl (/***/node_modules/postcss/lib/parser.js:203:25)
    at Parser.other (/***/node_modules/postcss/lib/parser.js:170:18)
    at Parser.loop (/***/node_modules/postcss/lib/parser.js:81:26)
    at parse (/***/node_modules/postcss/lib/parse.js:26:16)
    at new LazyResult (/***/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/***/node_modules/postcss/lib/processor.js:117:12)
    at repl:1:22
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
```

**Comment by ai** [comment]
@shinnn Thanks. I will fix error for `:` input.

**Comment by ai** [comment]
Close for https://github.com/postcss/postcss/issues/1004
