### ISSUE TITLE
Update `postcss` to v6

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-scss#59]
@ai We are preparing a release `stylelint` v8 (on `postcss` v6) :smile:

**Comment by ai** [comment]
Awesome. I will update it in next 2 hours

**Comment by ai** [comment]
Done https://github.com/postcss/postcss-scss/commit/eb82675109ebda6e83ac64dbd85474e45ac0576c

**Comment by ai** [comment]
Released in 1.0
