### ISSUE TITLE
This module does not compile SCSS

### ISSUE THREAD

**Issue by sagikazarmark** [postcss/postcss-scss#6]
I am a little bit confused about the purpose of this module. Let me ask a practical question: can I use this with the scss version of bootstrap?

**Comment by ai** [comment]
Not. This plugin compile SCSS to PostCSS AST. It do not execute mixins, math, etc. It just parse syntas as is.

It can be used to lint SCSS sources. Or to change workspaces. But not to compile SCSS to valid CSS.

**Comment by sagikazarmark** [comment]
Thanks
