### ISSUE TITLE
In sass nested at-rules without semicolon are valid

### ISSUE THREAD

**Issue by OEvgeny** [postcss/postcss-scss#7]
Noticed what in PostCSS we need to end nested ``at-rule`` with ``;`` but in SASS it works without it. See [this](https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_hover.scss#L6) as for example.

**Comment by OEvgeny** [comment]
Since it's ``postcss`` issue, we need to close this.

**Comment by ai** [comment]
Released in PostCSS 5.0.6. Just reinstall `postcss-scss` dependencies.

**Comment by OEvgeny** [comment]
Thanks!
