### ISSUE TITLE
duplicate properties with cssnext - conflict

### ISSUE THREAD

**Issue by infantito** [postcss/postcss-scss#70]
It happens when I use cssnext (#rrggbbaa) with postcss-scss and precss 

![image](https://user-images.githubusercontent.com/9045302/31191177-f972a1da-a902-11e7-9311-4c007d6b3505.png)

![image](https://user-images.githubusercontent.com/9045302/31191269-3803fd7c-a903-11e7-8651-2b775e315076.png)

![image](https://user-images.githubusercontent.com/9045302/31190880-1055cb58-a902-11e7-97e8-3dee02163fbc.png)

**Comment by ai** [comment]
This is how `hsla` polyfill works. Some browser in your `browsers` option does not support `rgba` syntax, so `cssnext` care about them and add old non-alpha polyfill.
