### ISSUE TITLE
Autoprefixer changed "height: 0;" to "height: ;"

### ISSUE THREAD

**Issue by Azragh** [postcss/postcss-scss#77]
As I was working on a "fixed aspect ratio layout" for WordPress gallery, I found this little nasty bug:

When I write this (in SCSS):
```
.gallery-icon {
  // 16:10:
  height: 0;
  line-height: 0;
  padding-top: 100% / 16 * 10;
}
```
After runnin' Autoprefixer the "0" after the inline comment gets removed! When I omit the ":", Autoprefixer adds ";" after the inline comment.. ;)

**Comment by ai** [comment]
How do you use Autoprefixer? (Most Autoprefixer use cases is to run Autoprefixer after SCSS transformation). 

What other PostCSS plugins do you have? How do you run PostCSS?

What if you will disable all PostCSS plugins?

**Comment by Azragh** [comment]
I use it right in my SCSS Files (manually), because I let the WP Plugin "WP-SCSS" do the compiling. So in my opinion there are no other PostCSS plugins involved..

**Comment by ai** [comment]
I need code examples. How to reproduce the issue.

It is just Atom plugin?

**Comment by Azragh** [comment]
Nothing too special going on here:
```
.gallery-item {
	position: relative;
	flex: 1 0 100%;
	margin: 0;
	border: 5px solid transparent;

	.gallery-icon {
	        // 16:10:
		height: 0;
		line-height: 0;
		padding-top: 100% / 16 * 10;

		a {
			position: absolute;
			top: 0;
			bottom: 0;
			width: 100%;
			overflow: hidden;
			img {
			    top: 50%;
			    object-fit: cover;
			    transform: translate(0, -50%);
			}
		}

		&.portrait {
			img {
			    position: relative;
			    min-width: 100%;
			    height: auto;
			}
		}

		&.landscape {
			img {
			    position: relative;
			    min-height: 100%;
			    min-width: 100%;
			}
		}
	}

	.gallery-caption {
		display: flex;
		align-items: center;
		justify-content: center;
		position: absolute;
	        top: 0;
	        left: 0;
	        bottom: 0;
	        width: 100%;
	        padding: 10px;
	        font-size: 1.4rem;
	        text-align: center;
	        color: #fff;
	        background-color: rgba($greyscale1, 0.85);
		pointer-events: none;
	        opacity: 0;
		transition: opacity 0.5s ease;
	}
	&:hover .gallery-caption {
		opacity: 1;
	}
}
```
And yes, only the Atom plugin - I'm not using it in any other way..

**Comment by ai** [comment]
I will try this SCSS source with parser when I will be at home. But honestly seems like Atom plugin uses wrong source type or have same other problem.

**Comment by Azragh** [comment]
This may be. I just thought I should report this because it's the first issue I since I'm working with Atom and Autoprefixer in combination. ;)

**Comment by ai** [comment]
I try this SCSS example and get this PostCSS AST:

```css
.gallery-icon {
  /* 16:10:*/
  height: 0;
  line-height: 0;
  padding-top: 100% / 16 * 10;
}
```

Everything was parsed correctly. Autoprefixer will not break anything here. Sorry, you should write to plugin author.
