### ISSUE TITLE
Skip converting inline comments

### ISSUE THREAD

**Issue by Hyzac** [postcss/postcss-scss#82]
I try to use this parser together with the css-declaration-sorter to sort the declarations in the sccs files. I also use KSS to generate documentation and this documentation is built up with inline comments. When parsing the files the parser replaces the inline comments with block comments making the KSS generator fail on styleguide generation. Is there a way to set this parser to skip converting inline comments?

**Comment by ai** [comment]
If you want to keep comments inline set PostCSS SCSS as syntax instead of parser: `syntax: require ("postcss-scss")`

**Comment by ai** [comment]
@Momoko-Sanchez show your code, small input, output and expected output

**Comment by Momoko-Sanchez** [comment]
Here's the linting function. I changed "parser" to "syntax", but the output stayed the same:

```
const postcssScss = require('postcss-scss');

const runLintOnFile = (path, basePath) => {
  return new Promise((resolve, reject) => {
    fs.readFile(path, (err, cssFileBuffer) => {
      if(err) {
        console.log(err);
        reject(err);
      }
      // Run linter on each file
      postcss(linterPlugin.linter( {basePath: basePath} ))
        .process(cssFileBuffer, { from: path, syntax: postcssScss })
        .then(result => {
          resolve(true);
        })
    })
  })
}```

leads to the following outputs (example)
from 
```
    padding: 0 !important; //required for qbt-ui```
to 
```
    padding: 0 !important; /*required for qbt-ui*/```

**Comment by ai** [comment]
@Momoko-Sanchez can’t reproduce:

```js
const postcssScss = require('postcss-scss');
const postcss = require('postcss')

const scss = 'a {\n' +
             '  padding: 0 !important; //required for qbt-ui\n' +
             '}'

postcss().process(scss, { from: undefined, syntax: postcssScss }).then(result => {
  console.log(result.content)
})
```

output:

```
a {
  padding: 0 !important; //required for qbt-ui
}
```

Maybe you should replace `resolve(true)` to `resolve(result.content)`?

**Comment by Momoko-Sanchez** [comment]
This didn't change it, unfortunately. There is more to the plugin, but unfortunately I can't share it, because it's in a proprietary repo. I'll try to find a clue or create a shareable version.
