### ISSUE TITLE
Custom theme (with scss file) creation generates error

### ISSUE THREAD

**Issue by lenouber** [postcss/postcss-scss#85]
I would like to create a custom theme for my new project.

1) I create a new file called custom-theme.scss in which I just write

@import "/_theming.scss";
I can't use @import '/theming'; because this file doesn't exist (@angular/cli: "1.6.7")

2) I add a new entry in .angular-cli.json

"styles": [
"styles.css",
"custom-theme.scss"
],

3) I add a line to my empty file styles.css:

@import "./custom-theme.scss";

I get following error:

ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./src/styles.css
Module build failed: Syntax Error

(326:17) Unknown word

324 | }
325 |

326 | box-shadow: #{map-get(_get-umbra-map($color), $zValue)},
| ^
327 | #{map-get(_get-penumbra-map($color), $zValue)},
328 | #{map-get(_get-ambient-map($color), $zValue)};

@ ./src/styles.css 4:14-138
@ multi ./src/styles.css ./src/custom-theme.scss

webpack: Failed to compile.

**Comment by ai** [comment]
Hi. I will look at this Friday.

**Comment by ai** [comment]
I tested this input and everything works :(

```sass
box-shadow: #{map-get(_get-umbra-map($color), $zValue)},
#{map-get(_get-penumbra-map($color), $zValue)},
#{map-get(_get-ambient-map($color), $zValue)};
```

Can you give me full SCSS input?

Also be sure that you use latest `postcss-scss` version.
