### ISSUE TITLE
sass fail to parse the following expression

### ISSUE THREAD

**Issue by ArielGueta** [postcss/postcss-scss#86]
Thanks for the library, I have a problem. I am getting the following error:

> sass fail to parse the following expression: get-function("

It's only happens with this plugin. When using webpack loader it's works fine. I think it's related to the node-sass version.

**Comment by ArielGueta** [comment]
```sass
@function json-encode($value) {
  $type: type-of($value);

  @if function-exists('_json-encode--#{$type}') {
    @return call(get-function('_json-encode--#{$type}', $value));
  }

  @error 'Unknown type for #{$value} (#{$type}).';
}
```

This is a valid scss. You can see the get-function in the [docs](http://sass-lang.com/documentation/Sass/Script/Functions.html).

**Comment by ai** [comment]
Work as expected https://runkit.com/embed/eeqrfzrchhf4

Your error is not a PostCSS error. Seems like it went from Sass.

**Comment by ArielGueta** [comment]
Thanks! I will open an issue.
