### ISSUE TITLE
Unknown word: // @import

### ISSUE THREAD

**Issue by aleclarson** [postcss/postcss-scss#88]
```js
const code = "// @import 'tachyons';"
require('postcss').parse(code, {
  syntax: require('postcss-scss')
})
```

In the above example, an "Unknown word" error is thrown.

`node-sass` works fine, though.

```js
require('node-sass').renderSync({
  data: "// @import 'tachyons';"
})
```

**Comment by ai** [comment]
Strange. Thanks.

**Comment by ai** [comment]
I will look only on next week. Must to prepare for conference.

**Comment by ai** [comment]
`poostcss.parse()` don’t have `syntax` option ;).

Only `postcss(plugins).process` has `syntax` option.

This code works fine:

```js
const code = "// @import 'tachyons';"
require('postcss-scss').parse(code)
```
