### ISSUE TITLE
Struggling to understand how to use this.

### ISSUE THREAD

**Issue by DanGamble89** [postcss/postcss-scss#9]
I have this gulp task:

```
return gulp.src(config.sass.src)
    // Initialise source maps
    .pipe($.sourcemaps.init())

    // Process our SCSS to CSS
    .pipe($.sass({
      precision: 10,
      stats: true,
      includePaths: ['node_modules/normalize.css/']
    }).on('error', $.sass.logError))

    .pipe($.postcss([stylelint(stylelintRules)])).process(scss, {syntax: syntax}).then(function (result) {
      result.content;
    })

    // PostCSS our vendor prefixes
//    .pipe($.postcss(postCSSProcessors))

    // Convert viable px units to REM
    .pipe($.pxtorem())

    // Write our source map, the root is needed for Django funnyness
    .pipe($.sourcemaps.write('./', {
      includeContent: false,
      sourceRoot: () => {
        return '../../static'
      }
    }))

    // Place our CSS in the location we link to
    .pipe(gulp.dest(config.css.dist))

    // Stream the changes to Browser Sync
    .pipe(browserSync.stream({match: '**/*.css'}))

    // Spit out the size to the console
    .pipe($.size({title: 'styles'}));
```

And obviously i'm getting `scss is not defined` if i change that to `'scss'` then i get `undefined is not a function`. Where does the `scss` variable come from in your example?

**Comment by TrySound** [comment]
@DanGamble89 scss syntax need to process scss files before sass. But need to cover all files. Stylelint should be added in separate task like here
https://github.com/TrySound/case/blob/master/gulpfile.js#L47-L58

**Comment by DanGamble89** [comment]
In that file you seem to be passing `main.css` with no kind of `.scss` from what i can see. I was wondering if i can use `stylelint` on my `.scss` files instead of the compiled `.css`

**Comment by TrySound** [comment]
@DanGamble89 My example is how to use stylelint. You just need to use another glob and pass postcss-scss as syntax.

**Comment by ai** [comment]
For this case you do not need to use `postcss-sass`. Just use `gulp-postcss`. This entire way is wrong, so remove it and use `gulp-postcss` docs examples to avoid mistakes.

**Comment by DanGamble89** [comment]
I've managed to get stylelint working :) I just wondered how i can get `scss` .process(scss, {syntax: syntax})

I tried it with just `gulp-postcss` as well but to no luck. I'll just keep trying i guess :)

**Comment by TrySound** [comment]
@DanGamble89 
```js
.pipe($.postcss(processors, options)
```

**Comment by DanGamble89** [comment]
That makes alot more sense to me, thanks :)
