### ISSUE TITLE
Support for data feature like in sass-loader

### ISSUE THREAD

**Issue by eddiesholl** [postcss/postcss-scss#91]
We're using a very handy feature from the `sass-loader` webpack plugin, the ability to tweak sass vars using build time env vars, passed in via a `data` option. Is there anyway this could be achieved using `postcss-loader` and `postcss-scss` as a parser? I'm looking at migrating over.

https://github.com/webpack-contrib/sass-loader#environment-variables

The only way I can imagine is to enhance `postcss-scss` to support it and inject it as a prefix before parsing.

**Comment by ai** [comment]
Hi. I have a bad news. This SCSS parser is not a compiler. It can't compile SCSS to CSS and apply Sass variables.

If you want this feature for PostCSS, you can look at postcss-simple-vars. And this plugin has `variables` option to pass predefined variables values.

Not note that postcss-simple-vars syntax is similar, but not 100% equal to Sass.
