### ISSUE TITLE
Add a note to tell people which thing _does_ compile scss?

### ISSUE THREAD

**Issue by Pomax** [postcss/postcss-scss#94]
Every google hit for "using postcss with sass" ends up bringing me here, so: is it possible to add a sentence to readme to say what I _do_ need if I want to use postcss to compile my .scss files into a single .css file? (because `postcss --parser postcss-scss -o main.css ./sass/*.scss` isn't it).

**Comment by ai** [comment]
Good idea. Can I ask you to send PR (writing docs is hard to me since I am not native speaker).

**Comment by Pomax** [comment]
I'll be happy to edit your text, but I _literally have no idea how to do this_ so I'm confused how you would expect me to be able to write that text...?

**Comment by ai** [comment]
:D It is depends on your builder. For webpack:

```js
    rules: [
      {
        test: /\.scss$/,
        use: [
          'style-loader',
          'css-loader',
          'postcss-loader',
          'sass-loader'
        ]
      }
    ]
```

For Gulp:

```js
  return gulp.src('./sass/**/*.scss')
    .pipe(sass().on('error', sass.logError))
    .pipe(postcss())
    .pipe(gulp.dest('./css'));
```

Unfortunately, there is the one-line solution for CLI (CLI is limited only for the simple cases).

**Comment by ai** [comment]
The main idea, you need you the standard Sass and compile SCSS to CSS before PostCSS.

**Comment by Pomax** [comment]
Okay, but now imagine I don't want any of that. I just want to use the cli. I'm looking for the exact opposite of "many files and build tools". I just want to say something similar to "postcss main.css ./sass/*.scss" and be done.

**Comment by ai** [comment]
In this case you need to pass every file first to `node-sass` CLI, then to PostCSS CLI (it is impossible to do it with one command, `postcss-scss` do not compile Sass).

Maybe something like this could work `node-sass src/*.scss --ouput - | postcss > dst/file.css`. You need some argument for Sass CLI to force it print output to `stdout`.

**Comment by Pomax** [comment]
thanks.
