### ISSUE TITLE
Support interpolation #{}

### ISSUE THREAD

**Issue by vithar** [postcss/postcss-scss#97]
```
"postcss": "7.0.14",
"postcss-scss": "2.0.0",
```

https://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_

I try to use this:

```
font: #{$font-size}/#{$line-height};
```

expect

```
font: 12px/30px;
```

in output but got

```
font: #{12px}/#{30px};
```

**Comment by ai** [comment]
`postcss-scss` is not SCSS → CSS compiler. It is just a parser. It parses `font: #{$font-size}/#{$line-height};` as a Declaration node with `font` property and `#{$font-size}/#{$line-height}` value. This parser was created to use tools like Stylelint for SCSS source (to do SCSS → SCSS transformations).

Seems like you are using `postcss-simple-vars` to interpolate `$vars`. Unfortunately, `postcss-simple-vars` was created for different syntax `$(font-size)/$(line-height)` or just `$font-size/$line-height`. Changing syntax will be breaking changes without good reasons for it.

If you really need to compile some SCSS features to CSS, you can write your own `postcss-scss-compiler` plugin. But if you will tell me more about your use case, I may suggest a better solution.

**Comment by vithar** [comment]
I just try to avoid division in case of `font: 12px / 30px`, I need exact the same result as written and try to find working solution to escape `/`.

**Comment by ai** [comment]
`postcss-simple-vars` doesn’t do any math operations. `$(font-size)/$(line-height)` will be converted to `12px/30px`.

**Comment by vithar** [comment]
But scss do math and I got `font: 0,4px`

**Comment by vithar** [comment]
I found my problem, it is `postcss-automath`

**Comment by vithar** [comment]
https://github.com/EverledgerIO/postcss-automath/issues/5
